config/routes.rb
FirstApp::Application.routes.draw do
  resources :users
  resource :session, only: [ :new, :create, :destroy ]
  get '/sandbox', to: 'root#sandbox' if Rails.env.development?
  root to:'root#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_save { self.session_token ||= Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s)}
	has_secure_password
	validates :name, presence: true,length: { maximum: 30 }
	validates :email, format: { with: /\A[^@]+@[^@]+\z/ }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def home
  end

  def sandbox
  	#session[:our_data] = 1234
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by_email(params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  		# sign-in our user
  		session[:session_token] = @user.session_token
  	  flash[:success] = "Welcome back, #{@name}!" 
  		redirect_to @user
  	else
  	    flash.now[:error] = "Invalid email/password combination"
  	    render "new"  	
    end
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
       #flash[:success] = "Welcome, #{@user.name}!"
        redirect_to @user, notice: "User was successfully created." 
      else
        render action: 'new' 
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user) #把用戶登入
        session[:session_token] = user.session_token
    end

    def sign_in? #用戶登入了嗎
    	!current_user_nil?
    end
    
    def current_user #現在登入的用戶
        @current_user ||= User.find_by_session_token(session[:session_token])
    end
    
    def current_user?(user) #這個用戶是現在登入的用戶嗎?
        current_user == user
    end         	
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name,class: "gravatar")
	end	
end

app/views/layouts/_footer.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
 <%= yield %>
  <%=# render :partial => "layouts/_footer" %>
  <%= #debug(params) if Rails.env.development? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- New header -->
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
    	<div class="container">
    		<%=link_to "FirstApp","#",id:"logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home", '#' %>
            <% if signed_in? %>
              <li><%= link_to "Users", '#' %>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.name %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                  <%= link_to "Sign_out", session_path, method: "delete" %>
                  </li>
                 </ul> 
                </li>
               <% else %>
                <li><%= link_to "Sign_in", new_session_path %></li>
               <% end %>
              </ul>
             </nav>       
    	</div>   
    </div>	
</header>

<!-- Content wrapped in container -->

<div class="container">
	<%= yield %>
<!-- New footer -->
<footer class="footer">
	<small>
		<a href=codecamp.io">程式開發工作營</a>
	</small>
</footer>
<!-- Debugging footer -->
<%= debug(params) if Rails.env.development? %>
</div>

<% if not @messages_rendered -%>
  <% if flash[:error] -%>
    <p class='error'><%=h flash[:error] %></p>
  <% end -%>
  <% if flash[:notice] -%>
    <p class='notice'><%=h flash[:notice] %></p>
  <% end -%>
  <% if flash[:success] -%>
    <p class='notice'><%=h flash[:success] %></p>
  <% end -%>
<% end -%>
<% @messages_rendered = true -%>


</body>
</html>

app/views/root/home.html.erb
<h1>Welcome to FirstApp</h1>
<center>
	<%= link_to "Sign_in","#",class:"btn btn-large btn-primary" %> <br>
	<%= link_to "Register!","#" %>
</center>

app/views/root/sandbox.html.erb
<%= session.inspect %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
	<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
        <div id="error_explanation">
        	<div class="alert alert-error">
        		There are <%= pluralize @user.errors.count,"error"	%>.
        	</div>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
          <% end %>
          </ul>
        </div> 
        <% end %> 

     <%= f.label :name %></br>
	 <%= f.text_field :name %>
	 </br>

	 <%= f.label :email %></br>
	 <%= f.text_field :email %>
     </br>

	 <%= f.label :password %></br>
	 <%= f.password_field :password %>
     </br> 

	 <%= f.label :password_confirmation %></br>
	 <%= f.password_field :password_confirmation %>
     </br></br>  
	 
	 <div>
	 	<%= f.submit "Register!", class: "btn btn-primary" %>
	 </div>
	<% end %>
</div> 	


<!-- <%= render 'form' %>

<%= link_to 'Back', users_path %>-->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>	

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>